import { useEffect, useState } from "react";
import { Boxes, Pencil, Search } from "lucide-react";
import AppLayout from "../../Layouts/AppLayout";
import useApi from "../../hooks/useApi";
import { Button } from "../../components/atoms";
import { FormField } from "../../components/molecules";
import { Drawer } from "../../components/organisms/Drawer";

const items = response => response?.data?.items || [];

export default function InventoryPage() {
    const api = useApi();
    const [rows, setRows] = useState([]); const [warehouses, setWarehouses] = useState([]);
    const [filters, setFilters] = useState({query:"",warehouse_id:"",stock_status:"all"});
    const [editing, setEditing] = useState(null); const [form, setForm] = useState({delta:0,reason:"",reorder_point:0});
    const [state, setState] = useState("loading"); const [error, setError] = useState("");
    const load = async () => { setState("loading"); try { const [inventory, warehouseList] = await Promise.all([api.inventory.list({...filters,stock_status:filters.stock_status === "all" ? undefined : filters.stock_status,per_page:100}),api.warehouses.list({status:"active",per_page:100})]); setRows(items(inventory)); setWarehouses(items(warehouseList)); setState("ready"); } catch { setState("error"); } };
    useEffect(() => { const timer=setTimeout(load,250); return()=>clearTimeout(timer); }, [filters.query,filters.warehouse_id,filters.stock_status]);
    const open = row => { setEditing(row); setForm({delta:0,reason:"",reorder_point:row.reorder_point}); };
    const save = async event => { event.preventDefault(); setError(""); try { if(Number(form.delta)!==0) await api.inventory.adjust({product_id:editing.product_id,warehouse_id:editing.warehouse_id,delta:Number(form.delta),reason:form.reason}); if(Number(form.reorder_point)!==Number(editing.reorder_point)) await api.inventory.update(editing.id,{reorder_point:Number(form.reorder_point)}); setEditing(null); await load(); } catch (e) { setError(e?.response?.data?.message || "No pudimos actualizar el inventario."); } };
    return <AppLayout title="Inventario"><div className="page-container"><header className="page-heading"><div><h1>Inventario</h1><p>Existencias, agotamientos y puntos de reorden por almacén.</p></div></header>
        <div className="toolbar"><label className="toolbar-search search-field"><Search size={17}/><input value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})} placeholder="Buscar producto o SKU"/></label><select value={filters.warehouse_id} onChange={e=>setFilters({...filters,warehouse_id:e.target.value})}><option value="">Todos los almacenes</option>{warehouses.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><select value={filters.stock_status} onChange={e=>setFilters({...filters,stock_status:e.target.value})}><option value="all">Todo el stock</option><option value="in_stock">Disponible</option><option value="low">Bajo reorden</option><option value="out">Agotado</option></select></div>
        {state==="error"?<div className="error-banner"><span>No pudimos cargar el inventario.</span><Button size="sm" onClick={load}>Reintentar</Button></div>:<div className="data-surface"><table className="responsive-table"><thead><tr><th>Producto</th><th>Almacén</th><th>Existencias</th><th>Reorden</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td data-label="Producto"><span className="product-cell"><span className="product-thumb thumb-empty"><Boxes size={18}/></span><span><strong>{row.product?.short_description}</strong><small>{row.product?.sku}</small></span></span></td><td data-label="Almacén">{row.warehouse?.name}</td><td data-label="Existencias"><strong>{row.stock}</strong></td><td data-label="Reorden">{row.reorder_point}</td><td data-label="Estado"><span className={`status ${row.stock<=0?"status--danger":row.stock<=row.reorder_point?"status--warning":"status--success"}`}>{row.stock<=0?"Agotado":row.stock<=row.reorder_point?"Reponer":"Disponible"}</span></td><td><button className="icon-only" onClick={()=>open(row)} aria-label={`Ajustar ${row.product?.short_description}`}><Pencil size={16}/></button></td></tr>)}</tbody></table>{state==="loading"&&<div className="empty-state">Actualizando existencias…</div>}{state==="ready"&&!rows.length&&<div className="empty-state">No hay inventario para estos filtros.</div>}</div>}
        <Drawer open={Boolean(editing)} title="Ajustar inventario" onClose={()=>setEditing(null)}><form onSubmit={save}><p><strong>{editing?.product?.short_description}</strong><br/>{editing?.warehouse?.name}</p>{error&&<div className="error-banner">{error}</div>}<div className="drawer-grid"><FormField label="Ajuste" type="number" value={form.delta} onChange={e=>setForm({...form,delta:e.target.value})}/><FormField label="Punto de reorden" type="number" min="0" value={form.reorder_point} onChange={e=>setForm({...form,reorder_point:e.target.value})}/><FormField className="span-2" as="textarea" label="Motivo del ajuste" required={Number(form.delta)!==0} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><div className="drawer-footer"><Button variant="secondary" type="button" onClick={()=>setEditing(null)}>Cancelar</Button><Button type="submit">Guardar ajuste</Button></div></form></Drawer>
    </div></AppLayout>;
}
