import { useEffect, useMemo, useState } from "react";
import { Line } from "react-chartjs-2";
import { Chart, CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Filler } from "chart.js";
import { Download, RefreshCw } from "lucide-react";
import AppLayout from "../../Layouts/AppLayout"; import useApi from "../../hooks/useApi"; import { Button, IconButton } from "../../components/atoms"; import { BestSellerTree } from "../../components/organisms/BestSellerTree"; import { GroupBuilder } from "../../components/molecules/GroupBuilder"; import { Tabs } from "../../components/molecules"; import { formatCurrency } from "../../utils/formatters";
Chart.register(CategoryScale,LinearScale,PointElement,LineElement,Tooltip,Filler);
const unwrap=r=>r?.data||r;const list=r=>r?.data?.items||r?.data||[];const iso=date=>date.toISOString().slice(0,10);const tabs=[['daily','Diario'],['weekly','Semanal'],['monthly','Mensual'],['seller','Por vendedor'],['overview','Resumen'],['best-sellers','Más vendidos']];
const readFilters=()=>{const q=new URLSearchParams(location.search);const to=new Date();const from=new Date();from.setDate(to.getDate()-29);return{from:q.get('from')||iso(from),to:q.get('to')||iso(to),warehouse_id:q.get('warehouse_id')||'',tab:q.get('tab')||'daily',group_by:q.getAll('group_by[]').length?q.getAll('group_by[]'):['category']}};
const Metric=({label,value,detail})=><article className="metric-card"><span className="metric-label">{label}</span><strong className="metric-value">{value}</strong><span className="metric-detail">{detail}</span></article>;
export default function ReportsPage(){const api=useApi();const[filters,setFilters]=useState(readFilters);const[warehouses,setWarehouses]=useState([]);const[definitions,setDefinitions]=useState([]);const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[nonce,setNonce]=useState(0);
 useEffect(()=>{Promise.all([api.warehouses.list({status:'all',per_page:100}),api.metadataDefinitions.list()]).then(([w,d])=>{setWarehouses(list(w));setDefinitions(list(d))})},[]);
 useEffect(()=>{const pop=()=>setFilters(readFilters());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
 const params=useMemo(()=>({from:filters.from,to:filters.to,warehouse_id:filters.warehouse_id||undefined,group_by:filters.group_by}),[filters]);
 useEffect(()=>{const q=new URLSearchParams();q.set('from',filters.from);q.set('to',filters.to);q.set('tab',filters.tab);if(filters.warehouse_id)q.set('warehouse_id',filters.warehouse_id);if(filters.tab==='best-sellers')filters.group_by.forEach(v=>q.append('group_by[]',v));history.replaceState({},'',`${location.pathname}?${q}`);setLoading(true);setError('');let request;const common={warehouse_id:filters.warehouse_id||undefined};if(filters.tab==='daily')request=api.reports.daily({...common,date:filters.to});else if(filters.tab==='weekly')request=api.reports.weekly({...common,week:filters.from});else if(filters.tab==='monthly')request=api.reports.monthly({...common,month:filters.from.slice(0,7)});else if(filters.tab==='seller')request=api.reports.bySeller({...common,from:filters.from,to:filters.to});else if(filters.tab==='overview')request=api.reports.overview(params);else request=api.reports.bestSellers(params);request.then(r=>setData(unwrap(r))).catch(e=>setError(e?.response?.data?.message||'No pudimos cargar el reporte.')).finally(()=>setLoading(false))},[filters,nonce]);
 const exportReport=format=>{if(['overview','best-sellers'].includes(filters.tab))location.assign(api.reports.exportUrl(filters.tab,format,params));else if(format==='csv'&&filters.tab==='daily')location.assign(`/api/v1/reports/daily/export?date=${filters.to}&warehouse_id=${filters.warehouse_id}`);else if(format==='csv'&&filters.tab==='seller')location.assign(`/api/v1/reports/by-seller/export?from=${filters.from}&to=${filters.to}&warehouse_id=${filters.warehouse_id}`);else setError('La exportación PDF está disponible en Resumen y Más vendidos.')};
 return <AppLayout title="Reportes"><div className="page-container"><header className="page-heading"><div><h1>Reportes</h1><p>Seis lecturas operativas con filtros y fuentes consistentes.</p></div><div className="page-actions"><Button variant="secondary" onClick={()=>exportReport('csv')}><Download size={16}/>CSV</Button><Button variant="secondary" onClick={()=>exportReport('pdf')}><Download size={16}/>PDF</Button></div></header><Tabs className="report-tabs" label="Tipo de reporte" items={tabs.map(([value,label])=>({value,label}))} value={filters.tab} onChange={tab=>setFilters(f=>({...f,tab}))}/><div className="report-controls"><label>Desde<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>Hasta<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Almacén<select value={filters.warehouse_id} onChange={e=>setFilters({...filters,warehouse_id:e.target.value})}><option value="">Todos</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><IconButton onClick={()=>setNonce(n=>n+1)} label="Actualizar"><RefreshCw size={17}/></IconButton></div>{filters.tab==='best-sellers'&&<GroupBuilder value={filters.group_by} definitions={definitions} onChange={group_by=>setFilters({...filters,group_by})}/>} {error&&<div className="error-banner">{error}</div>}{loading?<div className="empty-state">Actualizando reporte…</div>:<ReportContent tab={filters.tab} data={data}/>}</div></AppLayout>}
function ReportContent({tab,data}){if(tab==='daily')return <div className="metric-grid"><Metric label="Venta neta del día" value={formatCurrency(data?.total_net)} detail={data?.date}/><Metric label="Venta bruta" value={formatCurrency(data?.total_gross)} detail="Antes de descuentos"/><Metric label="Tickets" value={data?.sales||0} detail="Ventas cerradas"/></div>;if(tab==='weekly')return <Compare title="Semana" current={data?.current} previous={data?.previous}/>;if(tab==='monthly')return <Compare title="Mes" current={data?.current} previous={data?.previous}/>;if(tab==='seller')return <section className="data-surface"><table className="responsive-table"><thead><tr><th>Vendedor</th><th>Tickets</th><th>Total vendido</th></tr></thead><tbody>{(data||[]).map(row=><tr key={row.id}><td data-label="Vendedor">{row.seller_name}</td><td data-label="Tickets">{row.sales}</td><td data-label="Total">{formatCurrency(row.total)}</td></tr>)}</tbody></table>{!data?.length&&<div className="empty-state">Sin ventas por vendedor.</div>}</section>;if(tab==='best-sellers')return <Best data={data}/>;return <Overview data={data}/>}
const Compare=({title,current={},previous={}})=><><div className="metric-grid"><Metric label={`${title} actual`} value={formatCurrency(current.total)} detail={`${current.sales||0} tickets`}/><Metric label={`${title} anterior`} value={formatCurrency(previous.total)} detail={`${previous.sales||0} tickets`}/></div><section className="chart-surface"><h2 className="panel-title">Comparación directa</h2><div className="compare-bars"><div><span>Actual</span><strong>{formatCurrency(current.total)}</strong></div><div><span>Anterior</span><strong>{formatCurrency(previous.total)}</strong></div></div></section></>;
function Overview({data}){const s=data?.summary||{};const current=data?.series?.current||[];const previous=data?.series?.previous||[];const chart={labels:current.map(i=>i.date.slice(5)),datasets:[{label:'Actual',data:current.map(i=>i.total),borderColor:'#3d7bff',backgroundColor:'rgba(61,123,255,.12)',fill:true,tension:.3},{label:'Anterior',data:previous.map(i=>i.total),borderColor:'#8291a7',borderDash:[5,5]}]};return <><div className="metric-grid"><Metric label="Venta neta" value={formatCurrency(s.net_sales)} detail="Período actual"/><Metric label="Tickets" value={s.tickets||0} detail="Ventas cerradas"/><Metric label="Ticket promedio" value={formatCurrency(s.average_ticket)} detail="Por operación"/><Metric label="Estado" value="Actualizado" detail={data?.updated_at?new Date(data.updated_at).toLocaleString('es-MX'):'Ahora'}/></div><section className="chart-surface"><h2 className="panel-title">Venta neta por día</h2><p id="overview-summary" className="chart-summary">Comparación del período actual contra el anterior equivalente.</p><div className="chart-frame"><Line data={chart} aria-describedby="overview-summary" options={{responsive:true,maintainAspectRatio:false}}/></div></section></>}
const Best=({data})=><><div className="metric-grid"><Metric label="Unidades" value={data?.summary?.units||0} detail="Total deduplicado"/><Metric label="Venta neta" value={formatCurrency(data?.summary?.net_sales)} detail={`${data?.summary?.tickets||0} tickets`}/><Metric label="Productos" value={data?.summary?.products||0} detail="Con venta"/><Metric label="Stock" value={data?.summary?.stock||0} detail="Actual"/></div>{data?.non_additive_tag_totals&&<p className="tag-note">Los subtotales por tag no son aditivos; el total general está deduplicado.</p>}<section className="chart-surface"><h2 className="panel-title">Jerarquía de más vendidos</h2><BestSellerTree nodes={data?.tree||[]}/></section></>;
