/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a Swift Auth token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                token?: string;
                                user?: components["schemas"]["User"];
                            };
                        };
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List warehouses */
        get: {
            parameters: {
                query?: {
                    active?: boolean;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated warehouses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["Warehouse"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create warehouse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WarehouseInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Warehouse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update warehouse */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WarehouseInput"];
                };
            };
            responses: {
                /** @description Updated warehouse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Warehouse"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/product-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product types */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated product types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["ProductType"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create product type */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductTypeInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["ProductType"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-types/{productTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update product type */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productTypeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductTypeInput"];
                };
            };
            responses: {
                /** @description Updated type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["ProductType"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: {
            parameters: {
                query?: {
                    query?: string;
                    product_type_id?: string;
                    warehouse_id?: string;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["Product"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create product */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Product"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show product */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Product"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update product */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Product"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inventory records */
        get: {
            parameters: {
                query?: {
                    warehouse_id?: string;
                    product_id?: string;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated inventory items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["InventoryRecord"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Adjust inventory */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InventoryAdjustRequest"];
                };
            };
            responses: {
                /** @description Updated inventory */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["InventoryRecord"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/skus/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve SKUs from a seeded range */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReserveSkuRequest"];
                };
            };
            responses: {
                /** @description Reserved SKUs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                range_id?: string;
                                skus?: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List carts */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated carts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["Cart"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        warehouse_id: string;
                    };
                };
            };
            responses: {
                /** @description Created cart */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update cart metadata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CartUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/carts/{cartId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add product to cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CartItemRequest"];
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carts/{cartId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove cart item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update cart item */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CartItemRequest"];
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/carts/{cartId}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm sale for a cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckoutRequest"];
                };
            };
            responses: {
                /** @description Sale confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Sale"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sales */
        get: {
            parameters: {
                query?: {
                    warehouse_id?: string;
                    seller_id?: string;
                    from?: string;
                    to?: string;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["Sale"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{saleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show sale */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    saleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Sale"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales/{saleId}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend sale receipt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    saleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        channel: "email" | "sms";
                        destination: string;
                    };
                };
            };
            responses: {
                /** @description Receipt queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: {
            parameters: {
                query?: {
                    query?: string;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated customers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                items?: components["schemas"]["Customer"][];
                                pagination?: components["schemas"]["PaginatedMetadata"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create customer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Customer"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update customer */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerInput"];
                };
            };
            responses: {
                /** @description Updated customer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Customer"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/customers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remote customer self-registration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RemoteRegistrationRequest"];
                };
            };
            responses: {
                /** @description Customer updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Customer"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily KPIs */
        get: {
            parameters: {
                query?: {
                    date?: string;
                    warehouse_id?: string;
                    product_type_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPIs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                date?: string;
                                total_gross?: number;
                                total_net?: number;
                                sales?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly comparison */
        get: {
            parameters: {
                query?: {
                    week?: string;
                    warehouse_id?: string;
                    product_type_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weekly KPIs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                week?: string;
                                current?: {
                                    total?: number;
                                    sales?: number;
                                };
                                previous?: {
                                    total?: number;
                                    sales?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly comparison */
        get: {
            parameters: {
                query?: {
                    month?: string;
                    warehouse_id?: string;
                    product_type_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monthly KPIs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                month?: string;
                                current?: {
                                    total?: number;
                                    sales?: number;
                                };
                                previous?: {
                                    total?: number;
                                    sales?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/by-seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Totals per seller */
        get: {
            parameters: {
                query?: {
                    warehouse_id?: string;
                    product_type_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Seller ranking */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: {
                                id?: string;
                                seller_name?: string;
                                total?: number;
                                sales?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @example success */
            status?: string;
            message?: string;
            data?: unknown;
        };
        PaginatedMetadata: {
            current_page?: number;
            per_page?: number;
            total?: number;
        };
        Warehouse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            code?: string;
            active?: boolean;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        ProductType: {
            /** Format: uuid */
            id?: string;
            name?: string;
            code?: string;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Product: {
            /** Format: uuid */
            id?: string;
            sku?: string;
            short_description?: string;
            long_description?: string | null;
            photo_url?: string | null;
            /** Format: float */
            purchase_price?: number;
            /** Format: float */
            sale_price?: number;
            /** Format: date-time */
            entry_date?: string;
            /** Format: date-time */
            stock_end_date?: string | null;
            /** Format: uuid */
            product_type_id?: string;
            active?: boolean;
            type?: components["schemas"]["ProductType"];
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        InventoryRecord: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            product_id?: string;
            /** Format: uuid */
            warehouse_id?: string;
            stock?: number;
            reorder_point?: number;
            product?: components["schemas"]["Product"];
            warehouse?: components["schemas"]["Warehouse"];
        };
        CartItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            product_id?: string;
            quantity?: number;
            unit_price?: number;
            discount?: number;
            subtotal?: number;
            product?: components["schemas"]["Product"];
        };
        Cart: {
            /** Format: uuid */
            id?: string;
            visual_key?: string;
            user_id?: string;
            warehouse_id?: string;
            /** @enum {string} */
            status?: "active" | "paused" | "closed";
            total_gross?: number;
            discount_total?: number;
            total_net?: number;
            items?: components["schemas"]["CartItem"][];
            warehouse?: components["schemas"]["Warehouse"];
        };
        SaleItem: {
            id?: string;
            product_id?: string;
            sku?: string;
            description?: string;
            quantity?: number;
            unit_price?: number;
            discount?: number;
            subtotal?: number;
        };
        Customer: {
            id?: string;
            name?: string;
            email?: string | null;
            phone?: string | null;
            accepts_marketing?: boolean;
        };
        Sale: {
            id?: string;
            folio?: string;
            warehouse_id?: string;
            user_id?: string;
            customer_id?: string | null;
            /** @enum {string} */
            payment_method?: "cash" | "card" | "transfer" | "mixed";
            payment_details?: Record<string, never> | null;
            total_gross?: number;
            discount_total?: number;
            total_net?: number;
            /** Format: date-time */
            paid_at?: string;
            items?: components["schemas"]["SaleItem"][];
            customer?: components["schemas"]["Customer"];
            warehouse?: components["schemas"]["Warehouse"];
        };
        User: {
            id?: number;
            /** Format: uuid */
            uuid?: string;
            name?: string;
            email?: string;
            roles?: {
                id?: number;
                slug?: string;
                name?: string;
            }[];
        };
        AuthRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        WarehouseInput: {
            name: string;
            code: string;
            active?: boolean;
        };
        ProductTypeInput: {
            name: string;
            code: string;
        };
        ProductInput: {
            sku?: string;
            short_description: string;
            long_description?: string;
            photo_url?: string;
            purchase_price: number;
            sale_price: number;
            /** Format: date */
            entry_date: string;
            product_type_id: string;
            active?: boolean;
        };
        InventoryAdjustRequest: {
            product_id: string;
            warehouse_id: string;
            delta: number;
            reason?: string;
        };
        CartItemRequest: {
            product_id: string;
            quantity: number;
            unit_price?: number;
            discount?: number;
        };
        CartUpdateRequest: {
            discount_total?: number;
            /** @enum {string} */
            status?: "active" | "paused" | "closed";
        };
        CheckoutRequest: {
            /** @enum {string} */
            payment_method: "cash" | "card" | "transfer" | "mixed";
            payment_details?: Record<string, never>;
            customer_id?: string;
            receipt?: Record<string, never>;
        };
        CustomerInput: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            accepts_marketing?: boolean;
        };
        RemoteRegistrationRequest: components["schemas"]["CustomerInput"] & {
            token: string;
        };
        ReserveSkuRequest: {
            quantity: number;
            prefix?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
