<?php

return [
    'url' => env('CARONTE_URL', ''),
    'app_cn' => env('CARONTE_APP_CN', 'pos'),
    'app_secret' => env('CARONTE_APP_SECRET', ''),
    'application_group_id' => env('CARONTE_APPLICATION_GROUP_ID', ''),
    'application_group_secret' => env('CARONTE_APPLICATION_GROUP_SECRET', ''),
    'issuer_id' => env('CARONTE_ISSUER_ID', 'caronte'),
    'enforce_issuer' => true,
    'auth_mode' => 'oidc',
    'token_clock_skew_seconds' => (int) env('CARONTE_TOKEN_CLOCK_SKEW_SECONDS', 60),
    'oidc' => [
        'issuer' => env('CARONTE_OIDC_ISSUER', env('CARONTE_URL', '')),
        'client_id' => env('CARONTE_OIDC_CLIENT_ID', env('CARONTE_APP_CN', 'pos')),
        'client_secret' => env('CARONTE_OIDC_CLIENT_SECRET', ''),
        'redirect_uri' => env('CARONTE_OIDC_REDIRECT_URI', ''),
        'scopes' => 'openid profile email roles tenant',
        'jwks_cache_ttl' => (int) env('CARONTE_OIDC_JWKS_CACHE_TTL', 3600),
    ],
    'use_2fa' => false,
    'allow_http_requests' => env('CARONTE_ALLOW_HTTP_REQUESTS', false),
    'tls_verify' => true,
    'update_local_user' => false,
    'notification_delivery' => 'server',
    'session_key' => 'caronte.user_token',
    'routes_prefix' => 'auth',
    'success_url' => '/pos',
    'login_url' => '/auth/oidc/authorize',
    'routes' => ['login_url' => '/auth/oidc/authorize'],
    'http' => ['timeout' => 10, 'retries' => 1, 'retry_sleep' => 150],
    'roles' => [
        'pos-admin' => 'Administración completa del punto de venta',
        'pos-seller' => 'Operación de caja, clientes y ventas',
        'pos-auditor' => 'Consulta de ventas, reportes y auditoría',
    ],
    'permissions' => [],
    'management' => ['enabled' => false, 'access_roles' => ['pos-admin'], 'use_inertia' => true, 'features' => []],
    'use_inertia' => true,
    'table_prefix' => 'caronte_',
    'tenancy' => ['mode' => 'multi'],
];
